version: "3.2"
services:
  app:
    restart: unless-stopped
    build: 
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - media-volume:/data/media
  mongo:
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  nginx:
    restart: unless-stopped
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - media-volume:/data/media
volumes:
  media-volume:
