#Ports and volumes map HOST:CONTAINER

version: "3.2"
services:
  app:
    container_name: flask-server
    restart: unless-stopped
    build: 
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "9000"
    links:
      - mongo
    volumes:
      - ./data:/data
  mongo:
    container_name: mongo-database
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  nginx:
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:latest
    links:
      - app
        #volumes:
      #- ./data/static/html:/usr/share/nginx/html
    ports:
      - "80:80"
