#Ports and volumes map HOST:CONTAINER
#Everything in docker-compose file is on same network by default, can talk to each other using service name
#Links are deprecated and replaced by networks
#Service names used if container names aren't

version: "3.2"
services:
  app:
    restart: unless-stopped
    build: 
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - ./data:/data
  mongo:
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  nginx:
    restart: unless-stopped
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
